name: Detect Modular Profile
on: [push]

jobs:
  detect-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect Modular Profile
        run: |
          python3 detect_profile.py
